version: "3.11"
services:

  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/test_collection
      - MONGO_INITDB_DATABASE=test_collection
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db

  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      restart: always


  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo_db

